name: Create "Update Old Man's Beard status" video
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # # pull_request:
  #   branches: [ $default-branch ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: narakeet/build-video-github-action@v1.0.3
      id: video
      with:
        source-path: find-and-update-omb-video/script.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
        api-key: ${{ secrets.NARAKEET_API_KEY }}
    - uses: actions/upload-artifact@v1
      with:
        name: video
        path: "${{ steps.video.outputs.video-file }}"
