name: Create "Using the CAMS weed map" video
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # # pull_request:
  #   branches: [ $default-branch ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: narakeet/build-video-github-action@v1.0.5
      id: video
      with:
        source-path: using-cams-video/script.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
        api-key: ${{ secrets.NARAKEET_API_KEY }}
    - uses: actions/upload-artifact@v1
      with:
        name: video
        path: |
          "${{ steps.video.outputs.video-file }}"
          "${{ steps.video.outputs.srt-file }}"
          "${{ steps.video.outputs.poster-file }}"
